"""add org_id to clients

Revision ID: 0a2b92c9cf07
Revises: 245ef537b0d7
Create Date: 2025-12-27 09:43:17.214295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2b92c9cf07'
down_revision = '245ef537b0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_clients_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_org_id'))
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###
