"""add activities and activity_equipment m2m

Revision ID: 245ef537b0d7
Revises: 6429a2e6ab9a
Create Date: 2025-12-26 21:20:23.860496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245ef537b0d7'
down_revision = '6429a2e6ab9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('executor_user_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.Enum('SIMULADO', 'CONTROLADO', 'REAL', name='tipo_ambiente'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('machines_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(environment IN ('SIMULADO','CONTROLADO','REAL'))", name='ck_activities_environment'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['executor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_equipment',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 'equipment_id'),
    sa.UniqueConstraint('activity_id', 'equipment_id', name='uq_activity_equipment')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_equipment')
    op.drop_table('activities')
    # ### end Alembic commands ###
