"""add email and phone to stakeholders

Revision ID: dfd019ff6eb3
Revises: 0a2b92c9cf07
Create Date: 2026-01-03 12:10:00.071081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd019ff6eb3'
down_revision = '0a2b92c9cf07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakeholders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakeholders', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
